config/routes.rb
Rails.application.routes.draw do
  resources :recommendation_statuses
  resources :regions
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "users"

  resources :audit_reports do
    resources :recommendations, :evidences
    collection{post:import}
  end

  get '/sensitivities' => 'audit_reports#sensitivities'
  get '/recommendations' => 'recommendations#index'
  get '/annexe' => 'recommendations#annexe'
  get '/recommendations/export' => 'recommendations#export_csv', defaults: { format: 'csv'}

  resources :audit_types 
  resources :organizations do
    collection{post:import}
  end
  resources :categories do
    collection{post:import}
  end
  resources :ministries do
    collection{post:import}
  end

  get '/reports/ministries/control' => 'reports#control_ministries'
  get '/reports/ministries/verified' => 'reports#verified_ministries'
  get '/reports/organizations/control' => 'reports#control_organizations'
  get '/reports/organizations/verified' => 'reports#verified_organizations'
  get '/reports/categories/rootstatus' => 'reports#root_category_totals'
  get '/reports/categories/rootstatus/csv' => 'reports#root_category_totals_csv'
  get '/reports/categories/rootstatus/summary' => 'reports#root_category_totals_summary'
  get '/reports/recommendations/category' => 'reports#recommendation_categories'
  get '/reports/recommendations/category/csv' => 'reports#recommendation_categories_csv'
  get '/reports/recommendations/category/summary' => 'reports#recommendation_categories_summary'
  get '/reports/exports' => 'reports#exports'
  get '/reports/exports/all/csv' => 'reports#export_all_csv'
  #alhader
  get '/reports/rapport' => 'reports#rapport'
  get '/recommendations/rapport' => 'recommendations#rapport'
  root "audit_reports#index"
end

app/models/evidence.rb
class Evidence < ApplicationRecord
  belongs_to :audit_report
  has_many :recommendations, dependent: :nullify

  validates :title, presence: true
  validates_uniqueness_of :title,:message=>"Erreur de doublon"

  def self.import(file,report_id)
    xlsx = Roo::Spreadsheet.open(file.path)
    xlsx.each do |row|
        e=Evidence.new
        e.title=row[0]
        e.audit_report_id=report_id
         e.save!
    end
  end

end

app/controllers/evidences_controller.rb
class EvidencesController < ApplicationController
  before_action :set_evidence, only: [:show, :edit, :update, :destroy]

  def show
    authorize @evidence
    @recommendation = Recommendation.new()
    @recommendation.audit_report = @audit_report
  end

  def new
    @audit_report = AuditReport.find(params[:audit_report_id])
    @evidence = Evidence.new
    @evidence.audit_report = @audit_report
    authorize @evidence
  end

  def edit
    authorize @evidence
  end

  def create
    @audit_report = AuditReport.find(params[:audit_report_id])
    @evidence = @audit_report.evidences.create(evidence_params)
    authorize @evidence

    if @evidence.save
      flash[:notice] = I18n.t("evidence.save_success")
      redirect_to audit_report_path(@audit_report)
    else
      render 'new'
    end
  end

  def update
      authorize @evidence
       
      if @evidence.update(evidence_params)
        flash[:notice] = I18n.t("evidence.save_success")
        redirect_to @audit_report
      else
        render 'edit'
      end
    end

  def destroy
    authorize @evidence
    @evidence.destroy
    redirect_to audit_report_path(@audit_report)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evidence
      @evidence = Evidence.find(params[:id])
      @audit_report = @evidence.audit_report
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evidence_params
      params.require(:evidence).permit(:title, :text, :audit_report_id)
    end
end

app/helpers/evidences_helper.rb
module EvidencesHelper
end

app/views/evidences/_evidence.html.erb
<tr>
  <td>
    <%= link_to evidence.title, audit_report_evidence_path(evidence.audit_report, evidence) %>
  </td>

  <td>
    <% if policy(evidence).update? %>
      <span class="float-right"><%= link_to t('navigation.edit'), edit_audit_report_evidence_path(evidence.audit_report, evidence), class: "btn btn-primary btn-sm" %></span>
    <% end %>
  </td>
</tr>

app/views/evidences/_form.html.erb
<%= form_with(model: [ @audit_report, @evidence ], local: true) do |form| %>
  <% if @evidence.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@evidence.errors.count, t('errors.error')) %> 
        <%= t('errors.prohibited_evidence') %>
      </h2>
      <ul>
        <% @evidence.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label  :title %><br>
      <%= form.text_area :title, class: "form-control" %>
    </div>
  </div>


  <% if current_page?(new_audit_report_evidence_path(@audit_report))%>
    <%= form.submit t('navigation.save', model: Evidence.model_name.human), class: "btn btn-primary" %>
  <% else %>
    <%= form.submit t('navigation.save', model: Evidence.model_name.human), class: "btn btn-primary" %>
    <% if policy(@evidence).destroy? %>
      <span class="float-right"><%= link_to t('navigation.delete'), [@evidence.audit_report, @evidence],
              method: :delete,
              data: { confirm: t('warnings.are_you_sure') }, class: "btn btn-danger" %></span>
    <% end %>
  <% end %>
  <%= link_to t('navigation.back'), audit_report_path(@audit_report), class: "btn btn-secondary" %>

<% end %>

app/views/evidences/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('evidence.edit') %></h5>
    <%= render 'form' %>
  </div>
</div>

app/views/evidences/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('evidence.add') %></h5>
    <%= render 'form' %>
  </div>
</div>

app/views/evidences/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @evidence.audit_report.title %> - <%= t('evidence.show') %></h5>
    <p>
    <strong><%=t('activerecord.attributes.evidence.title') %>:</strong>
    <%= @evidence.title %>
    </p>
  
    <% if policy(@evidence).update? %>
      <%= link_to t('navigation.edit'), edit_audit_report_evidence_path(@audit_report, @evidence), class: "btn btn-primary"  %>
    <% end %>
    <%= link_to t('navigation.back'), audit_report_path(@audit_report), class: "btn btn-secondary" %>
  </div>
</div>

<br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('recommendation.list') %></h5>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <!--<th></th>-->
            <th><%=t('activerecord.attributes.recommendation.title') %></th>
            <th><%=t('activerecord.attributes.recommendation.cost') %></th>
            <th><%=t('activerecord.attributes.recommendation.recovered') %></th>
            <th><%=t('activerecord.attributes.recommendation.status') %></th>
            <th>
              <% if policy(@recommendation).create? %>
                <span class="float-right"><%= link_to t('recommendation.add'), new_audit_report_recommendation_path(@audit_report), class: "btn btn-success btn-sm" %></span>
              <% end %> 
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render @evidence.recommendations %>
        </tbody>
      </table>
    </div>
  </div>
</div>