config/routes.rb
Rails.application.routes.draw do
  resources :recommendation_statuses
  resources :regions
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "users"

  resources :audit_reports do
    resources :recommendations, :evidences
    collection{post:import}
  end

  get '/sensitivities' => 'audit_reports#sensitivities'
  get '/recommendations' => 'recommendations#index'
  get '/annexe' => 'recommendations#annexe'
  get '/recommendations/export' => 'recommendations#export_csv', defaults: { format: 'csv'}

  resources :audit_types 
  resources :organizations do
    collection{post:import}
  end
  resources :categories do
    collection{post:import}
  end
  resources :ministries do
    collection{post:import}
  end

  get '/reports/ministries/control' => 'reports#control_ministries'
  get '/reports/ministries/verified' => 'reports#verified_ministries'
  get '/reports/organizations/control' => 'reports#control_organizations'
  get '/reports/organizations/verified' => 'reports#verified_organizations'
  get '/reports/categories/rootstatus' => 'reports#root_category_totals'
  get '/reports/categories/rootstatus/csv' => 'reports#root_category_totals_csv'
  get '/reports/categories/rootstatus/summary' => 'reports#root_category_totals_summary'
  get '/reports/recommendations/category' => 'reports#recommendation_categories'
  get '/reports/recommendations/category/csv' => 'reports#recommendation_categories_csv'
  get '/reports/recommendations/category/summary' => 'reports#recommendation_categories_summary'
  get '/reports/exports' => 'reports#exports'
  get '/reports/exports/all/csv' => 'reports#export_all_csv'
  #alhader
  get '/reports/rapport' => 'reports#rapport'
  get '/recommendations/rapport' => 'recommendations#rapport'
  root "audit_reports#index"
end

app/models/recommendation.rb
require 'csv'
class Recommendation < ApplicationRecord
  scope :year, -> (year) { joins('INNER JOIN audit_reports ON audit_reports.id = recommendations.audit_report_id').where('audit_reports.year = ' + year)  }
  scope :sensitivity, -> (sensitivity) { joins(:audit_report).where(audit_reports: {sensitivity: sensitivity})  }
  scope :user, -> (user_id) { joins('INNER JOIN audit_reports ON audit_reports.id = recommendations.audit_report_id').where('audit_reports.user_id = ' + user_id) }
  scope :control, -> (control_organization_id) { joins('INNER JOIN audit_reports ON audit_reports.id = recommendations.audit_report_id').where('audit_reports.control_organization_id = ' + control_organization_id) }
  scope :verified, -> (verified_organization_id) { joins('INNER JOIN audit_reports ON audit_reports.id = recommendations.audit_report_id').where('audit_reports.verified_organization_id = ' + verified_organization_id) }
  #scope :status, -> (status) { where("recommendations.status = '" + status + "'" ) }
  scope :ministry, -> (ministry_id) { joins('INNER JOIN organizations ON audit_reports.verified_organization_id = organizations.id').where('organizations.ministry_id = ' + ministry_id) }
  scope :status, -> (status_id) { joins("INNER JOIN recommendation_statuses ON recommendations.recommendation_status_id = recommendation_statuses.id").where("recommendation_statuses.id = '" + status_id + "'" ) }
  scope :report, -> (report) { joins('INNER JOIN audit_reports ON audit_reports.id = recommendations.audit_report_id').where('audit_reports.id = ' + report) }

  include Filterable
  #using postgreSQL enum type: https://www.sitepoint.com/enumerated-types-with-activerecord-and-postgresql/
  enum status: {
      complete:  'complete',
      incomplete: 'incomplete',
      ongoing: 'ongoing',
      unknown: 'unknown'
  }

  belongs_to :audit_report
  belongs_to :evidence, optional: true
  has_and_belongs_to_many :categories
  belongs_to :recommendation_status
  validates_uniqueness_of :title, scope: :audit_report
  validates :title, presence: true
  validates :category_ids, presence: true
  #validates :text, presence: true

  def self.filtered_recommendations(filter_params, to_csv=false)
      recommendations = Recommendation
        .joins(:recommendation_status, audit_report: [:control_organization, {verified_organization: :ministry}])
        .includes(:recommendation_status, audit_report: [:control_organization, {verified_organization: :ministry}])
        .filters(filter_params)
        .order("audit_reports.year", "ministries.name", "verified_organizations_audit_reports.name", "organizations.name")

      if to_csv
        CSV.generate do |csv|
          csv << [I18n.t('activerecord.attributes.ministry.name'), I18n.t('activerecord.attributes.audit_report.verified_organization'), I18n.t('activerecord.attributes.audit_report.control_organization'), I18n.t('activerecord.attributes.recommendation.year'), I18n.t('activerecord.attributes.recommendation.title'), I18n.t('activerecord.attributes.recommendation.status'), I18n.t('activerecord.attributes.recommendation.cost'), I18n.t("activerecord.attributes.recommendation.recovered")]
          recommendations.each do |r|
            csv << [r.audit_report.verified_organization.ministry.name, r.audit_report.verified_organization.name, r.audit_report.control_organization.name, r.audit_report.year, r.title, r.recommendation_status.name, r.cost, r.recovered]
          end
        end
      else 
        return recommendations
      end 
  end
  #===== REPORT FUNCTIONS ======
  def self.recommendations_with_categories(year, status, to_csv=false, to_summary=false)
    recommendations = "
      WITH root_categories AS (
        SELECT  
          c2.id AS category_id, 
          c1.id AS root_category_id, 
          c2.name AS category_name, 
          c1.name AS root_category_name
        FROM public.categories c1 
        INNER JOIN public.categories c2 ON c2.ancestry = c1.id::text OR c2.ancestry LIKE c1.id::text || '/%' 
        UNION
        SELECT 
          id AS category_id, 
          id AS root_category_id, 
          name AS category_name, 
          name AS root_category_name
        FROM public.categories 
        WHERE ancestry is null
      )
      SELECT DISTINCT 
        r.id, 
        ar.year, 
        r.title, 
        r.cost, 
        r.recovered, 
        rs.name as recommendation_status_name, 
        rc.root_category_name, 
        rc.root_category_id, 
        rc.category_name,
		    rc.category_id,
        r.audit_report_id, 
        r.evidence_id,
		    vo.name as verified_organization,
        co.name as control_organization,
        vm.name as verified_ministry
      FROM recommendations r 
      INNER JOIN recommendation_statuses rs ON rs.id = r.recommendation_status_id
      INNER JOIN audit_reports ar ON r.audit_report_id = ar.id
      INNER JOIN organizations vo ON ar.verified_organization_id = vo.id
      INNER JOIN organizations co ON ar.control_organization_id = co.id
      INNER JOIN ministries vm ON vo.ministry_id = vm.id
      INNER JOIN categories_recommendations cr ON cr.recommendation_id = r.id
      INNER JOIN root_categories rc ON rc.category_id = cr.category_id
      WHERE 0=0
      "
      recommendations = recommendations + " AND ar.year= " + year if !year.nil? && year.length > 0
      recommendations = recommendations + " AND rs.id= " + status  if !status.nil? && status.length > 0
      recommendations = recommendations + "
      ORDER BY audit_report_id, id, root_category_id
      "

    recommendations = Recommendation.find_by_sql(recommendations)

    if to_csv
      CSV.generate do |csv|
        csv << [I18n.t('activerecord.attributes.recommendation.title'), I18n.t('activerecord.attributes.audit_report.year'), I18n.t('activerecord.attributes.recommendation.cost'), I18n.t("activerecord.attributes.recommendation.recovered"), I18n.t('activerecord.attributes.recommendation.status'), I18n.t("activerecord.models.category"), I18n.t("activerecord.models.category"),I18n.t('activerecord.attributes.audit_report.control_organization'),I18n.t('activerecord.models.ministry'),I18n.t('activerecord.attributes.audit_report.verified_organization')]
        recommendations.each do |r|
          csv << [r.title, r.year, r.cost, r.recovered, r.recommendation_status_name, r.root_category_name, r.category_name,r.control_organization,r.verified_ministry,r.verified_organization]
        end
      end
    elsif to_summary
      cats = {}
      total_cost = 0
      total_recovered = 0
      total_count = 0
      recommendations.each do |c|
        !c.cost ? cost = 0 : cost = c.cost.to_i
        !c.recovered ? recovered = 0 : recovered = c.recovered.to_i
        if !cats[c.category_name]
          cats[c.category_name] = {:count => 1,:cost => cost,:recovered => recovered} 
        else
          cats[c.category_name][:count] = cats[c.category_name][:count] + 1
          cats[c.category_name][:cost] = cats[c.category_name][:cost] + cost
          cats[c.category_name][:recovered] = cats[c.category_name][:recovered] + recovered
        end
        total_cost = total_cost + cost
        total_recovered = total_recovered + recovered
        total_count = total_count + 1
      end
      return {:categories => cats, :total_cost => total_cost, :total_recovered => total_recovered, :total_count => total_count}

    else 
      return recommendations
    end 
  end

  def self.import(file,report_id)
    xlsx = Roo::Spreadsheet.open(file.path)
    xlsx.each do |row|
        r=Recommendation.new
        r.title=row[0]
        r.text=row[1]
        r.cost=row[2]
        r.recovered=row[3]
        r.recommendation_status_id=row[4]
        if row[5].present?
          #r.evidence_id=row[5]
        end
        r.justification=row[6]
        r.response=row[7]
        r.category_ids=3
        r.audit_report_id=report_id
        r.save!
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
    def index
      if current_user.user?
        params[:user] = current_user.id.to_s
      end
      @users=User.all
      @reports=AuditReport.all
      if params[:user]
        @recommendations = Recommendation.filtered_recommendations(params.slice(:user, :control, :verified, :year, :status, :sensitivity,:ministry,:report))
      end
      respond_to do |format|
        format.xlsx {
          response.headers[
            'Content-Disposition'
          ] = "attachment; filename=recommendation.xlsx"
        }
        format.html { render :index }
      end
    end

    def export_csv
      authorize  Recommendation.new
      @recommendations = Recommendation.filtered_recommendations(params.slice(:user, :control, :verified, :year, :status, :sensitivity,:ministry,:report), to_csv=true)
      send_data @recommendations, :filename => 'recommendations.csv'
    end

    def annexe 
      @categories = Category.aggregates_by_root_status(params[:year], to_csv=false, to_summary_csv=true)
      @counts = AuditReport.summary_counts(params[:year])
      @reports=AuditReport.all
      @recommendations = Recommendation.filtered_recommendations(params.slice(:user, :control, :verified, :year, :status, :sensitivity,:ministry,:report))
      render 'annexe'
    end

    def show
      @audit_report = AuditReport.find(params[:audit_report_id])
      @recommendation = Recommendation.find(params[:id])
      authorize @recommendation
    end

    def new
      @audit_report = AuditReport.find(params[:audit_report_id])
      @recommendation = Recommendation.new
      @recommendation.audit_report = @audit_report
      authorize @recommendation
    end

    def edit
      @audit_report = AuditReport.find(params[:audit_report_id])
      @recommendation = Recommendation.find(params[:id])
      authorize @recommendation
    end

    def create
      @audit_report = AuditReport.find(params[:audit_report_id])
      @recommendation = @audit_report.recommendations.create(recommendation_params)
      authorize @recommendation

      if @recommendation.save
        flash[:notice] = I18n.t("recommendation.save_success")
        redirect_to action: "edit", id: @recommendation.id, audit_report_id: params[:audit_report_id]
        #redirect_to audit_report_path(@audit_report)
      else
        render 'new'
      end
    end

    def update
      @audit_report = AuditReport.find(params[:audit_report_id])
      @recommendation = Recommendation.find(params[:id])
      authorize @recommendation
       
      if @recommendation.update(recommendation_params)
        flash[:notice] = I18n.t("recommendation.save_success")
        redirect_to action: "edit", id: params[:id], audit_report_id: params[:audit_report_id]
        #redirect_to @audit_report
      else
        render 'edit'
      end
    end

    def destroy
      @audit_report = AuditReport.find(params[:audit_report_id])
      @recommendation = @audit_report.recommendations.find(params[:id])
      authorize @recommendation
      @recommendation.destroy
      redirect_to audit_report_path(@audit_report)
    end
    #alhader
    def rapport
      @categories = Category.aggregates_by_root_status(params[:year], to_csv=false, to_summary_csv=true)
      @counts = AuditReport.summary_counts(params[:year])
      @recommendations = Recommendation.recommendations_with_categories(params[:year], params[:status], to_csv=false, to_summary=true)
    end
     
     private
        def recommendation_params
          params.require(:recommendation).permit(:title, :evidence_id, :text, :year, :reason, :justification, 
            :response, :cost, :recovered, :status, :recommendation_status_id, :category_ids => [])
        end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
    def localized_statuses
        Hash[Recommendation.statuses.map { |k,v| [Recommendation.human_attribute_name("status.#{k}"), k] }]
    end
end

app/views/recommendations/_filters.html.erb
<%= form_tag recommendations_path, :method => :get do %>
  <div class="form-row">
    <div class="form-group col-md-2">
    <% if !current_user.user? %>
      <%= label_tag  t('activerecord.attributes.audit_report.user') %><br>
      <%= select_tag "user", options_for_select(@users.collect{ |u| [u.first_name+" "+u.last_name, u.id] }, params[:user]), include_blank: t('navigation.all'), class: "form-control selectpicker", "data-live-search" => "true" %>
    <% end %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.audit_report.sensitivity') %><br>
      <%= select_tag "sensitivity", options_for_select(localized_sensitivities, params[:sensitivity]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
  <div class="form-group col-md-2">
    <% if !current_user.user? %>
      <%= label_tag  t('activerecord.attributes.audit_report.title') %><br>
      <%= select_tag "report", options_for_select(@reports.collect{ |r| [r.title, r.id] }, params[:report]), include_blank: t('navigation.all'), class: "form-control selectpicker", "data-live-search" => "true" %>
    <% end %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.audit_report.control_organization') %><br>
      <%= select_tag "control", options_for_select(Organization.control().to_option_values, params[:control]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
     <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.audit_report.verified_organization') %><br>
      <%= select_tag "verified", options_for_select(Organization.verified().to_option_values, params[:verified]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.models.ministry') %><br>
      <%= select_tag "ministry", options_for_select(Ministry.to_option_values, params[:ministry]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.audit_report.year') %><br>
      <%= select_tag "year", options_for_select(Time.new.year-5..Time.new.year+5, params[:year]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.recommendation.status') %><br>
      <%= select_tag "status", options_for_select(RecommendationStatus.to_option_values, params[:status]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
    <div class="form-group col-md-1">
      <%= label_tag  t('navigation.filter') %><br>

      <button class='btn btn-primary form-control'>
        <i class="fa fa-filter"></i>
      </button>
    </div>
  </div>

<% end %>

app/views/recommendations/_form.html.erb
<%= form_with(model: [ @audit_report, @recommendation ], local: true) do |form| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recommendation.errors.count, t('errors.error')) %> 
        <%= t('errors.prohibited_recommendation') %>
      </h2>
      <ul>
        <% @recommendation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label  :title %><span class="text-danger">*</span><br>
      <%= form.text_area :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label  :text %><br>
      <%= form.text_field :text, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= form.label  :categories %><br>
      <%= form.collection_select(:category_ids, Category.arrange_as_array, :id, :name_for_selects, {}, { class: "chosen-select", multiple: true }) %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= form.label :cost %><br>
      <%= form.number_field :cost, class: "form-control", step: :any %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :recovered %><br>
      <%= form.number_field :recovered, class: "form-control", step: :any %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :status %><br>
      <%= form.collection_select :recommendation_status_id, RecommendationStatus.order(:name),:id,:name, {}, { :class => "form-control" } %>
    </div>
  </div>

    <div class="form-group">
      <%= form.label  :evidence %><br>
      <%= form.collection_select :evidence_id, @audit_report.evidences,:id,:title, {prompt: t('activerecord.attributes.recommendation.evidence')}, { :class => "form-control" } %>
    </div>


  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label  :response %><br>
      <%= form.text_area :response, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label  :justification %><br>
      <%= form.text_area :justification, class: "form-control" %>
    </div>
  </div>

  <% if current_page?(new_audit_report_recommendation_path(@audit_report))%>
    <%= form.submit t('recommendation.save', model: Recommendation.model_name.human), class: "btn btn-primary" %>
  <% else %>
    <%= form.submit t('recommendation.save', model: Recommendation.model_name.human), class: "btn btn-primary" %>
    <% if policy(@recommendation).destroy? %>
      <span class="float-right"><%= link_to t('navigation.delete'), [@recommendation.audit_report, @recommendation],
              method: :delete,
              data: { confirm: t('warnings.are_you_sure') }, class: "btn btn-danger" %></span>
    <% end %>
  <% end %>
  <%= link_to t('navigation.back'), audit_report_path(@audit_report), class: "btn btn-secondary" %>

<% end %>

app/views/recommendations/_recommendation.html.erb
<tr>
  <td>
    <%= link_to recommendation.title, audit_report_recommendation_path(recommendation.audit_report, recommendation) %>
  </td>
  <td>
    <%= recommendation.cost %>
  </td>
  <td>
    <%= recommendation.recovered %>
  </td>
  <td>
    <%= recommendation.recommendation_status.name %>
  </td>
  <td>
    <% if policy(recommendation).update? %>
      <span class="float-right"><%= link_to t('navigation.edit'), edit_audit_report_recommendation_path(recommendation.audit_report, recommendation), class: "btn btn-primary btn-sm" %></span>
    <% end %>
  </td>
</tr>

app/views/recommendations/edit.html.erb
<div class="card">
  <div class="card-body">
  <span class="float-right"><%= link_to t('recommendation.add'), new_audit_report_recommendation_path(@audit_report), class: "btn btn-success btn-sm" %></span>
    <h5 class="card-title"><%= t('recommendation.edit') %></h5>
    <%= render 'form' %>
  </div>
</div>

app/views/recommendations/index.html.erb
<%
  statut_non_parvenu=RecommendationStatus.where(name:'Non Parvenu').first
  stnp=statut_non_parvenu.id
  statut_execute=RecommendationStatus.where(name:'Exécutée').first
  stexec=statut_execute.id
  statut_non_execute=RecommendationStatus.where(name:'Non Exécutée').first
  st_n_exec= statut_non_execute.id
  status_encours=RecommendationStatus.where(name:'En Cours').first
  st_encours=status_encours.id
  

%>
<div class="card">
  <div class="card-body">
    <%= render "filters" %>
  </div>
</div>
<br />
<div class="card">
  <div class="card-body">
  
    <h5 class="card-title"><%= t('recommendation.list') %></h5>
  <div class="text-right">
  <%if @recommendations%>
  <% if policy(@recommendations).export_csv? %>
                  <div class="dropdown">
                    <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">Générer
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li>      <a class="text text-dark" href=<%="/recommendations/rapport/?year="+params[:year].to_s+"&status="+params[:status].to_s%>><%="Générer le  rapport"%></a></li>
                      <li><a class="text text-dark" href="annexe?utf8=✓&user=<%=params[:user]%>&sensitivity=<%=params[:sensitivity]%>&report=<%=params[:report]%>&control=<%=params[:control]%>&verified=<%=params[:verified]%>&ministry=<%=params[:ministry]%>&year=<%=params[:year]%>&status=<%=stnp%>">Liste des recommandations non parvenue</a></li>
                      <li><a class="text text-dark"  href="annexe?utf8=✓&user=<%=params[:user]%>&sensitivity=<%=params[:sensitivity]%>&report=<%=params[:report]%>&control=<%=params[:control]%>&verified=<%=params[:verified]%>&ministry=<%=params[:ministry]%>&year=<%=params[:year]%>&status=<%=stexec%>">Liste des recommandations exécutées</a></li>
                      <li><a class="text text-dark" href="annexe?utf8=✓&user=<%=params[:user]%>&sensitivity=<%=params[:sensitivity]%>&report=<%=params[:report]%>&control=<%=params[:control]%>&verified=<%=params[:verified]%>&ministry=<%=params[:ministry]%>&year=<%=params[:year]%>&status=<%=st_n_exec%>">Liste des recommandations non exécutées</a></li>
                      <li><a class="text text-dark" href="annexe?utf8=✓&user=<%=params[:user]%>&sensitivity=<%=params[:sensitivity]%>&report=<%=params[:report]%>&control=<%=params[:control]%>&verified=<%=params[:verified]%>&ministry=<%=params[:ministry]%>&year=<%=params[:year]%>&status=<%=st_encours%>">Liste des recommandations en cours d'exécutions</a></li>
                      <li><a class="text text-dark" href=<%="/recommendations/export?year="+params[:year].to_s+"&user="+params[:user].to_s+"&control="+params[:control].to_s+"&verified="+params[:verified].to_s+"&sensitivity="+params[:sensitivity].to_s%>><%=t('reports.export') %></a></li>
                    </ul>
                  </div>
      <% end %>
      <% end %>
      </div><br>
    <div class="table-responsive">
      <table class="table table-striped table-sm" id="auditReportsList">
        <thead>
          <tr>
            <th><%=t('activerecord.attributes.recommendation.title') %></th>
            <th><%=t('activerecord.attributes.audit_report.control_organization') %></th>
            <th><%=t('activerecord.attributes.audit_report.verified_organization') %></th>
            <th><%=t('activerecord.attributes.ministry.name') %></th>
            <th><%=t('activerecord.attributes.recommendation.cost') %></th>
            <th><%=t('activerecord.attributes.recommendation.recovered') %></th>
            <th><%=t('activerecord.attributes.recommendation.status') %></th>
            <th>
            </th>
          </tr>
        </thead>
        <tbody>
        <% if @recommendations%>
        <% @recommendations.each do |recommendation| %>
          <tr>
            <td>
              <%= link_to recommendation.title, audit_report_recommendation_path(recommendation.audit_report, recommendation) %>
            </td>
            <td>
              <%= recommendation.audit_report.control_organization.name %>
            </td>
            <td>
              <%= recommendation.audit_report.verified_organization.name %>
            </td>
            <td>
              <%= recommendation.audit_report.verified_organization.ministry.name %>
            </td>
            <td>
              <%= recommendation.cost %>
            </td>
            <td>
              <%= recommendation.recovered %>
            </td>
            <td>
              <%= recommendation.recommendation_status.name %>
            </td>
            <td>
              <% if policy(recommendation).update? %>
                <span class="float-right"><%= link_to t('navigation.edit'), edit_audit_report_recommendation_path(recommendation.audit_report, recommendation), class: "btn btn-primary btn-sm" %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/recommendations/new.html.erb
<div class="card">
  <div class="card-body">
  <span class="float-right"><%= link_to t('recommendation.add'), new_audit_report_recommendation_path(@audit_report), class: "btn btn-success btn-sm" %></span>
  <h5 class="card-title"><%= t('recommendation.add') %></h5>
    <%= render 'form' %>
  </div>
</div>

app/views/recommendations/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @recommendation.audit_report.title %> - <%= t('recommendation.show') %></h5>
    <p>
    <strong><%=t('activerecord.attributes.recommendation.title') %>:</strong>
    <%= @recommendation.title %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.recommendation.text') %>:</strong>
    <%= @recommendation.text %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.recommendation.reason') %>:</strong>
    <%= @recommendation.reason %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.recommendation.justification') %>:</strong>
    <%= @recommendation.justification %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.recommendation.response') %>:</strong>
    <%= @recommendation.response %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.recommendation.cost') %>:</strong>
    <%= @recommendation.cost %>
    </p>
    <p>
    <strong><%=t("activerecord.attributes.recommendation.recovered") %>:</strong>
    <%= @recommendation.recovered %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.recommendation.status') %>:</strong>
    <%= @recommendation.recommendation_status.name %>
    </p>
    <p>
    <strong><%=t("activerecord.attributes.recommendation.categories") %>:</strong>
    <% @recommendation.categories.each_with_index do |r,i| %>
      <%= r.name %><% if i != @recommendation.categories.size - 1 %>, <% end %>
    <% end %>
    </p>

    <% if policy(@recommendation).update? %>
      <%= link_to t('navigation.edit'), edit_audit_report_recommendation_path(@audit_report, @recommendation), class: "btn btn-primary"  %>
    <% end %>
    <%= link_to t('navigation.back'), audit_report_path(@audit_report), class: "btn btn-secondary" %>
  </div>
</div>