config/routes.rb
Rails.application.routes.draw do
  resources :recommendation_statuses
  resources :regions
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "users"

  resources :audit_reports do
    resources :recommendations, :evidences
    collection{post:import}
  end

  get '/sensitivities' => 'audit_reports#sensitivities'
  get '/recommendations' => 'recommendations#index'
  get '/annexe' => 'recommendations#annexe'
  get '/recommendations/export' => 'recommendations#export_csv', defaults: { format: 'csv'}

  resources :audit_types 
  resources :organizations do
    collection{post:import}
  end
  resources :categories do
    collection{post:import}
  end
  resources :ministries do
    collection{post:import}
  end

  get '/reports/ministries/control' => 'reports#control_ministries'
  get '/reports/ministries/verified' => 'reports#verified_ministries'
  get '/reports/organizations/control' => 'reports#control_organizations'
  get '/reports/organizations/verified' => 'reports#verified_organizations'
  get '/reports/categories/rootstatus' => 'reports#root_category_totals'
  get '/reports/categories/rootstatus/csv' => 'reports#root_category_totals_csv'
  get '/reports/categories/rootstatus/summary' => 'reports#root_category_totals_summary'
  get '/reports/recommendations/category' => 'reports#recommendation_categories'
  get '/reports/recommendations/category/csv' => 'reports#recommendation_categories_csv'
  get '/reports/recommendations/category/summary' => 'reports#recommendation_categories_summary'
  get '/reports/exports' => 'reports#exports'
  get '/reports/exports/all/csv' => 'reports#export_all_csv'
  #alhader
  get '/reports/rapport' => 'reports#rapport'
  get '/recommendations/rapport' => 'recommendations#rapport'
  root "audit_reports#index"
end

app/models/audit_report.rb
class AuditReport < ApplicationRecord
  mount_uploaders :reports, ReportUploader

  scope :year, -> (year) { where year: year }
  scope :user, -> (user_id) { where user_id: user_id }
  scope :type, -> (audit_type_id) { where audit_type_id: audit_type_id }
  scope :sensitivity, -> (sensitivity) { where sensitivity: sensitivity }
  scope :control, -> (control_organization_id) { where control_organization_id: control_organization_id }
  scope :verified, -> (verified_organization_id) { where verified_organization_id: verified_organization_id }
  scope :ministry, -> (ministry_id) { joins('INNER JOIN organizations ON audit_reports.verified_organization_id = organizations.id').where('organizations.ministry_id = ' + ministry_id) }
  
  include Filterable
  
  #using postgreSQL enum type: https://www.sitepoint.com/enumerated-types-with-activerecord-and-postgresql/
  enum sensitivity: {
      high:  'high',
      low:   'low'
  }

  has_many :recommendations, dependent: :destroy
  has_many :evidences, dependent: :destroy
  

  belongs_to :control_organization, :class_name => 'Organization'
  belongs_to :verified_organization, :class_name => 'Organization'
  belongs_to :audit_type
  belongs_to :user

  validates :title, presence: true
  validates :control_organization, presence: true
  validates :year, presence: true
  validates_uniqueness_of :title,scope: [:year, :verified_organization_id,:control_organization_id,:audit_type_id]
  def self.get_form_labels
    labels = {
          :title => I18n.t('activerecord.attributes.audit_report.title'),
          :recipient => I18n.t('activerecord.attributes.audit_report.recipient'),
          :text => I18n.t('activerecord.attributes.audit_report.text'),
          :year => I18n.t('activerecord.attributes.audit_report.year'),
          :period => I18n.t('activerecord.attributes.audit_report.period'),
          :audit_type => I18n.t('activerecord.attributes.audit_report.audit_type'),
          :control_organization => I18n.t('activerecord.attributes.audit_report.control_organization'),
          :verified_organization => I18n.t('activerecord.attributes.audit_report.verified_organization'),
          :user => I18n.t('activerecord.attributes.audit_report.user'),
          :sensitivity => I18n.t('activerecord.attributes.audit_report.sensitivity'),
          :arrival_date => I18n.t('activerecord.attributes.audit_report.arrival_date'),
          :assignment_date => I18n.t('activerecord.attributes.audit_report.assignment_date'),
          :received_date => I18n.t('activerecord.attributes.audit_report.received_date'),
          :confirmation_date => I18n.t('activerecord.attributes.audit_report.confirmation_date'),
          :required_field => I18n.t('errors.required_field'),
          :required_fields => I18n.t('errors.required_fields'),
          :save_success => I18n.t("audit_report.save_success"),
          :save_fail => I18n.t("audit_report.save_fail"),
          :new => I18n.t("audit_report.new"),
          :edit => I18n.t("audit_report.edit"),
          :cancel => I18n.t("navigation.cancel"),
          :add_organization => I18n.t("organization.add"),
          :organization_name => I18n.t("activerecord.attributes.organization.name"),
          :organization_abbreviation => I18n.t("activerecord.attributes.organization.abbreviation"),
          :ministry => I18n.t("activerecord.models.ministry"),
          :region => I18n.t("activerecord.models.region"),
          :add => I18n.t("navigation.add"),
        }
  end

  #===== REPORT FUNCTIONS ======
  def self.summary_counts(year)
    counts = "
    WITH rec_counts AS (
      SELECT 
        COUNT(distinct ar.id) AS audit_report_count,
        COUNT(r.id) AS recommendation_count,
        COUNT (distinct o.id) AS entity_count,
        SUM(CASE WHEN rs.name = 'Aucune Réponse' THEN 1 ELSE 0 END) AS unknown_status_count,
        SUM(CASE WHEN rs.name = 'Exécutée' THEN 1 ELSE 0 END) AS executed_status_count,
        SUM(CASE WHEN rs.name = 'En Cours' THEN 1 ELSE 0 END) AS in_progress_status_count,
        SUM(CASE WHEN rs.name = 'Non Exécutée' THEN 1 ELSE 0 END) AS not_executed_status_count
      FROM audit_reports ar
      INNER JOIN recommendations r ON r.audit_report_id = ar.id
      INNER JOIN organizations o ON o.id = ar.verified_organization_id
      INNER JOIN audit_types at ON at.id = ar.audit_type_id 
      INNER JOIN recommendation_statuses rs ON rs.id = r.recommendation_status_id
      WHERE 0=0
      "
      counts = counts + " AND ar.year= " + year if !year.nil? && year.length > 0
      counts = counts + "
    ),
    ar_counts AS (
      SELECT
        SUM(CASE WHEN at.name = 'Performance' THEN 1 ELSE 0 END) AS performance_count,
        SUM(CASE WHEN at.name = 'Financier' THEN 1 ELSE 0 END) AS finance_count
        FROM audit_reports ar
        INNER JOIN audit_types at ON at.id = ar.audit_type_id 
      WHERE 0=0
      "
      counts = counts + " AND ar.year= " + year if !year.nil? && year.length > 0
      counts = counts + "
    )
    SELECT 
      audit_report_count,
      recommendation_count,
      entity_count,
      performance_count,
      finance_count,
      unknown_status_count,
      executed_status_count,
      in_progress_status_count,
      not_executed_status_count
    FROM rec_counts, ar_counts
    "

    data_array = ActiveRecord::Base.connection.execute(counts).values[0]

    data = {
        :audit_report_count => data_array[0], 
        :recommendation_count => data_array[1], 
        :entity_count => data_array[2], 
        :performance_count => data_array[3],
        :finance_count => data_array[4],
        :unknown_status_count => data_array[5],
        :executed_status_count => data_array[6],
        :in_progress_status_count => data_array[7],
        :not_executed_status_count => data_array[8]
    }

  end 


  def self.export_all
    audit_reports = "
      SELECT 
        ar.id, 
        ar.year,
        ar.title, 
        ar.text, 
        ar.period, 
        ar.control_organization_id, 
        ar.verified_organization_id, 
        ar.audit_type_id, 
        aut.name as audit_type_name,
        ar.arrival_date, 
        ar.assignment_date, 
        ar.received_date, 
        ar.confirmation_date, 
        ar.completion_date, 
        ar.user_id, 
        u.email as user_email,
		    u.first_name as user_first_name,
		    u.last_name as user_last_name,
        ar.sensitivity,
        vo.name as verified_organization_name,
        vo.abbreviation as verified_organization_abbreviation,
        co.name as control_organization_name,
        co.abbreviation as control_organization_abbreviation,
        vm.id as verified_ministry_id,
        vm.name as verified_ministry_name,
        vm.abbreviation as verified_ministry_abbreviation,
        cm.id as control_ministry_id,
        cm.name as control_ministry_name,
        cm.abbreviation as control_ministry_abbreviation,
        r.id as recommendation_id,
        r.title as recommendation_title,
        r.text as recommendation_text,
        r.reason,
        r.cost,
        r.recovered,
        r.justification,
        r.response, 
        rs.id as status_id,
        rs.name as status,
        e.id as evidence_id,
		    e.title as evidence_title,
		    e.text as evidence_text,
		    cr.category_id,
		    c.name as category_name
      FROM
        audit_reports ar
      INNER JOIN audit_types aut ON ar.audit_type_id = aut.id
      INNER JOIN users u ON ar.user_id = u.id
      INNER JOIN organizations vo ON ar.verified_organization_id = vo.id
      INNER JOIN organizations co ON ar.control_organization_id = co.id
      INNER JOIN ministries vm ON vo.ministry_id = vm.id
      INNER JOIN ministries cm ON co.ministry_id = cm.id
      LEFT JOIN recommendations r ON r.audit_report_id = ar.id
      LEFT JOIN recommendation_statuses rs ON rs.id = r.recommendation_status_id
      LEFT JOIN evidences e on e.id = r.evidence_id
	    LEFT JOIN categories_recommendations cr ON r.id = cr.recommendation_id
	    LEFT JOIN categories c ON c.id = cr.category_id
	    ORDER BY ar.id, r.id, e.id, c.id
      "

    audit_reports = AuditReport.find_by_sql(audit_reports)

    CSV.generate do |csv|
      csv << [I18n.t('activerecord.attributes.audit_report.id'), 
              I18n.t('activerecord.attributes.audit_report.year'), 
              I18n.t('activerecord.attributes.audit_report.title'),
              I18n.t('activerecord.attributes.audit_report.text'),
              I18n.t('activerecord.attributes.audit_report.period'),
              I18n.t('activerecord.attributes.audit_report.control_organization') + ' ID',
              I18n.t('activerecord.attributes.audit_report.verified_organization') + ' ID',
              I18n.t('activerecord.attributes.audit_report.audit_type')  + ' ID',
              I18n.t('activerecord.attributes.audit_report.audit_type'),
              I18n.t('activerecord.attributes.audit_report.arrival_date'),
              I18n.t('activerecord.attributes.audit_report.assignment_date'),
              I18n.t('activerecord.attributes.audit_report.received_date'),
              I18n.t('activerecord.attributes.audit_report.confirmation_date'),
              I18n.t('activerecord.attributes.audit_report.completion_date'),
              I18n.t('activerecord.models.user') + ' ID',
              I18n.t('activerecord.attributes.user.email'),
              I18n.t('activerecord.attributes.user.first_name'),
              I18n.t('activerecord.attributes.user.last_name'),
              I18n.t('activerecord.attributes.audit_report.sensitivity'),
              I18n.t('activerecord.attributes.audit_report.verified_organization'),
              I18n.t('activerecord.attributes.audit_report.verified_organization_abbreviation'),
              I18n.t('activerecord.attributes.audit_report.control_organization'),
              I18n.t('activerecord.attributes.audit_report.control_organization_abbreviation'),

app/controllers/audit_reports_controller.rb
class AuditReportsController < ApplicationController
    def index

     if current_user.user?
            params[:user] = current_user.id.to_s
        end
        @users=User.all
        if params[:user]
          @audit_reports = AuditReport.joins(:control_organization, {verified_organization: :ministry}, :audit_type, :user).filters(params.slice(:user, :control, :verified, :year, :ministry)).includes(:control_organization, {verified_organization: :ministry}, :audit_type, :user)
        end
      
    end

    def sensitivities
        @sensitivities = Hash[AuditReport.sensitivities.map { |k,v| [v, AuditReport.human_attribute_name("sensitivity.#{k}")] }]
        render json: @sensitivities, status: :ok
    end

    def show
        @audit_report = AuditReport.find(params[:id])
        authorize @audit_report
        @recommendation = Recommendation.new()
        @recommendation.audit_report = @audit_report
        @evidence = Evidence.new()
        @evidence.audit_report = @audit_report

    end

    def new
        @audit_report = AuditReport.new
        authorize @audit_report
        @labels = AuditReport.get_form_labels
    end

    def edit
        @audit_report = AuditReport.find(params[:id])
        authorize @audit_report
        @labels = AuditReport.get_form_labels
    end

    def create
        @audit_report = AuditReport.new(audit_report_params)
        authorize @audit_report
        if @audit_report.save
          render json: @audit_report, status: :ok
        else
          render json: @audit_report.errors, status: :unprocessable_entity
        end
    end

    def update
        @audit_report = AuditReport.find(params[:id])
        authorize @audit_report
        unless @audit_report.update(audit_report_params)
          render json: @audit_report.errors, status: :unprocessable_entity
        end
    end

    def destroy
        @audit_report = AuditReport.find(params[:id])
        @audit_report.destroy
        redirect_to audit_reports_path
    end
    #alhader
  
  
  def import
    require 'csv'
    require 'roo'
    #@audit_report= AuditReport.import(params[:file])
    spreadsheet =Roo::Spreadsheet.open(params[:file])
    header = spreadsheet.row(1)
    i=0
   spreadsheet.each do |row|
    i+=1
        control=Organization.where({abbreviation: row[1]}).or(Organization.where({name: row[1]})).first
        entite=Organization.where({abbreviation: row[2]}).or(Organization.where({name: row[2]})).first
        audit=AuditType.where({name:row[3]}).first
        user=User.where({email:row[5]}).first

        @audit_report= AuditReport.new
        @audit_report.title=row[0]
        if defined?(control.id)
           @audit_report.control_organization_id=control.id
        end
        if defined?(entite.id)
           @audit_report.verified_organization_id=entite.id
        end
        if defined?(audit.id)
           @audit_report.audit_type_id=audit.id
        end
        if defined?(user.id)
           @audit_report.user_id=user.id
        end
        @audit_report.year=row[4]
        @audit_report.save      
        if @audit_report.errors.any?
          @audit_report.errors.add :base, :invalid, message: "Ligne en question "+i.to_s
        else
          redirect_to root_url, notice: "Rapports importés avec succès."
        end
    end  
      
    end
  
      private
          def audit_report_params
              params.require(:audit_report).permit(:title, :text, :year, :period, :control_organization_id, 
                  :verified_organization_id, :audit_type_id, :arrival_date, :assignment_date, :received_date, 
                  :confirmation_date, :completion_date, :user_id, :sensitivity, :recipient, {reports: []})
          end
  end

app/helpers/audit_reports_helper.rb
module AuditReportsHelper
    def localized_sensitivities
      Hash[AuditReport.sensitivities.map { |k,v| [AuditReport.human_attribute_name("sensitivity.#{k}"), v] }]
    end
end

app/views/audit_reports/_filters.html.erb
<%= form_tag audit_reports_path, :method => :get do %>
  <div class="form-row">
    <div class="form-group col-md-2">
      <% if !current_user.user? %>
        <%= label_tag  t('activerecord.attributes.audit_report.user') %><br>
        <%= select_tag "user", options_for_select(@users.collect{ |u| [u.first_name+" "+u.last_name, u.id] }, params[:user]), include_blank: t('navigation.all'), class: "form-control selectpicker", "data-live-search" => "true" %>
      <% end %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.audit_report.control_organization') %><br>
      <%= select_tag "control", options_for_select(Organization.control().to_option_values, params[:control]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.models.ministry') %><br>
      <%= select_tag "ministry", options_for_select(Ministry.to_option_values, params[:ministry]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
     <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.audit_report.verified_organization') %><br>
      <%= select_tag "verified", options_for_select(Organization.verified().to_option_values, params[:verified]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag  t('activerecord.attributes.audit_report.year') %><br>
      <%= select_tag "year", options_for_select(Time.new.year-5..Time.new.year+5, params[:year]), include_blank: t('navigation.all'), class: 'form-control' %>
    </div>
    <div class="form-group col-md-1">
      <%= label_tag  t('navigation.filter') %><br>

      <button class='btn btn-primary form-control'>
        <i class="fa fa-filter"></i>
      </button>
    </div>
  </div>

<% end %>

app/views/audit_reports/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('audit_report.edit') %></h5>
    <% if policy(AuditReport).create? %>
    <span  class="float-right"><%= link_to t('audit_report.new'), new_audit_report_path, class: "btn btn-lg btn-success btn-sm", id: "addAuditReport" %></span>
<% end %>
    <%= react_component('AuditReportForm', 
          {auditReport: @audit_report, 
          authenticityToken: form_authenticity_token, 
          labels: @labels}) %>

    <% if policy(@audit_report).destroy? %>
      <span  class="float-right"><%= link_to t('navigation.delete'), audit_report_path(@audit_report),
                method: :delete,
                data: { confirm: t('warnings.are_you_sure') }, class: "btn btn-danger" %></span>
    <% end %>
  </div>
   
</div>

app/views/audit_reports/index.html.erb
<div class="card">
  <div class="card-body">
    <%= render "filters" %>
  </div>
</div>
<br />
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('audit_report.list') %></h5>
    <div class="table-responsive">
      <table class="table table-striped table-sm" id="auditReportsList">
        <thead>
          <tr>
            <th><%=t('activerecord.attributes.audit_report.title') %></th>
            <th><%=t('activerecord.attributes.audit_report.control_organization') %></th>
            <th><%=t('activerecord.models.ministry') %></th>
            <th><%=t('activerecord.attributes.audit_report.verified_organization') %></th>
            <th><%=t('activerecord.attributes.audit_report.year') %></th>
            <th><%=t('activerecord.attributes.audit_report.sensitivity') %></th>
            <th><%=t('activerecord.attributes.audit_report.audit_type') %></th>
            <th>
              <% if policy(AuditReport).create? %>
                <span  class="float-right"><%= link_to t('audit_report.new'), new_audit_report_path, class: "btn btn-success btn-sm", id: "addAuditReport" %></span>
              <% end %>
            </th>
          </tr>
        </thead>
        <tbody>
        <% if @audit_reports%>
        <% @audit_reports.each do |ar| %>
          <tr>
            <td><%= link_to ar.title, audit_report_path(ar) %></td>
            <td><i class="fa fa-search" data-toggle="tooltip" data-placement="right"  title="<%= ar.control_organization.name %>"></i> <%= ar.control_organization.abbreviation %></td>
            <td><i class="fa fa-search" data-toggle="tooltip" data-placement="right"  title="<%= ar.verified_organization.ministry.name %>"></i> <%= ar.verified_organization.ministry.abbreviation %></td>
            <td><i class="fa fa-search" data-toggle="tooltip" data-placement="right"  title="<%= ar.verified_organization.name %>"></i> <%= ar.verified_organization.abbreviation %></td>
            <td><%= ar.year %></td>
            <td><%= AuditReport.human_attribute_name("sensitivity.#{ar.sensitivity}")  %></td>
            <td><%= ar.audit_type.name %></td>
            <td>
              <% if policy(ar).update? %>
                <span  class="float-right"><%= link_to t('navigation.edit'), edit_audit_report_path(ar), class: "btn btn-primary btn-sm" %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
        <% end %>
        </tbody>
      </table>
    </div>


 <% if policy(AuditReport).create? %>
<h2>Importer des rapports</h2>

<%= form_tag import_audit_reports_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<% end %>

  </div>
</div>

  </div>
</div>
<br>

app/views/audit_reports/new.html.erb
<div class="card">
  <div class="card-body">
  <% if policy(AuditReport).create? %>
      <div class="float-right">
            <%= link_to t('audit_report.new'), new_audit_report_path, class: "btn btn-success btn-sm", id: "addAuditReport" %></span>
      </div>
  <% end %>
    <h5 class="card-title"><%= t('audit_report.new') %></h5>
    <%= react_component('AuditReportForm', 
          {auditReport: @audit_report, 
          authenticityToken: form_authenticity_token, 
          labels: @labels}) %>
  </div>
</div>

app/views/audit_reports/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('audit_report.show') %></h5>

    <dl class="row">
      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.title') %></dt>
      <dd class="col-sm-9"><%= @audit_report.title %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.recipient') %></dt>
      <dd class="col-sm-9"><%= @audit_report.recipient %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.text') %></dt>
      <dd class="col-sm-9"><%= @audit_report.text %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.year') %></dt>
      <dd class="col-sm-3"><%= @audit_report.year %>&nbsp;</dd>
      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.period') %></dt>
      <dd class="col-sm-3"><%= @audit_report.period %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.audit_type') %></dt>
      <dd class="col-sm-9"><%= @audit_report.audit_type.name %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.control_organization') %></dt>
      <dd class="col-sm-9"><%= @audit_report.control_organization.name %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.verified_organization') %></dt>
      <dd class="col-sm-9"><%= @audit_report.verified_organization.name %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.arrival_date') %></dt>
      <dd class="col-sm-3"><%= @audit_report.arrival_date %>&nbsp;</dd>
      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.assignment_date') %></dt>
      <dd class="col-sm-3"><%= @audit_report.assignment_date %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.received_date') %></dt>
      <dd class="col-sm-3"><%= @audit_report.received_date %>&nbsp;</dd>
      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.confirmation_date') %></dt>
      <dd class="col-sm-3"><%= @audit_report.confirmation_date %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.completion_date') %></dt>
      <dd class="col-sm-9"><%= @audit_report.completion_date %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.user') %></dt>
      <dd class="col-sm-9"><%= @audit_report.user.email %>&nbsp;</dd>

      <dt class="col-sm-3"><%=t('activerecord.attributes.audit_report.sensitivity') %></dt>
      <dd class="col-sm-9"><%= AuditReport.human_attribute_name("sensitivity.#{@audit_report.sensitivity}")  %>&nbsp;</dd>

    </dl>

    <% if policy(@audit_report).update? %>
      <%= link_to t('navigation.edit'), edit_audit_report_path(@audit_report), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<br/>

<% if @audit_report.reports.length > 0 %>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%=t('activerecord.attributes.audit_report.reports') %></h5>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <tbody>
          <% @audit_report.reports.each do |r| %>
            <tr><td><%= link_to r.identifier, r.url, target: :_blank %></td></tr>
          <% end %>
          
        </tbody>
      </table>
    </div>
  </div>
</div>

<br/>
<% end %>
<br/>
<div class="card">
  <div class="card-body"><% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recommendation.errors.count, t('errors.error')) %> 
        <%= t('errors.prohibited_recommendation') %>
      </h2>
      <ul>
        <% @recommendation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <h5 class="card-title" data-toggle="tooltip"><%= t('activerecord.attributes.import.title_recommandation')%></h5>
        <%= form_with(url: {action: :import}, multipart: true) do %>
            <%= file_field_tag 'file' %>
            <%= hidden_field_tag :id, params[:id]%>
            <%= hidden_field_tag :type, 'recommandation'%>
            <%= submit_tag t('activerecord.attributes.import.bouton'),class: "btn btn-success" %>
        <% end %>
    </div>

</div>
<br/>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('recommendation.list') %></h5>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <!--<th></th>-->
            <th><%=t('activerecord.attributes.recommendation.title') %></th>
            <th><%=t('activerecord.attributes.recommendation.cost') %></th>
            <th><%=t('activerecord.attributes.recommendation.recovered') %></th>
            <th><%=t('activerecord.attributes.recommendation.status') %></th>
            <th>
              <% if policy(@recommendation).create? %>
                <span class="float-right"><%= link_to t('recommendation.add'), new_audit_report_recommendation_path(@audit_report), class: "btn btn-success btn-sm" %></span>
              <% end %> 
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render @audit_report.recommendations %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br/>
<br/>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('activerecord.attributes.import.title_evidence')%></h5>
        <%= form_with(url: {action: :import}, multipart: true) do %>
            <%= file_field_tag 'file' %>
            <%= hidden_field_tag :id, params[:id]%>
            <%= hidden_field_tag :type, 'evidence'%>
            <%= submit_tag t('activerecord.attributes.import.bouton'),class: "btn btn-success" %>
        <% end %>
    </div>
</div>
<br/>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('evidence.list') %></h5>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <!--<th></th>-->
            <th><%=t('activerecord.attributes.evidence.title') %></th>
            <th>
              <% if policy(@evidence).create? %>
                <span class="float-right"><%= link_to t('evidence.add'), new_audit_report_evidence_path(@audit_report), class: "btn btn-success btn-sm" %></span>
              <% end %> 
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render @audit_report.evidences %>
        </tbody>
      </table>
    </div>
  </div>
</div>