config/routes.rb
Rails.application.routes.draw do
  resources :recommendation_statuses
  resources :regions
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "users"

  resources :audit_reports do
    resources :recommendations, :evidences
    collection{post:import}
  end

  get '/sensitivities' => 'audit_reports#sensitivities'
  get '/recommendations' => 'recommendations#index'
  get '/annexe' => 'recommendations#annexe'
  get '/recommendations/export' => 'recommendations#export_csv', defaults: { format: 'csv'}

  resources :audit_types 
  resources :organizations do
    collection{post:import}
  end
  resources :categories do
    collection{post:import}
  end
  resources :ministries do
    collection{post:import}
  end

  get '/reports/ministries/control' => 'reports#control_ministries'
  get '/reports/ministries/verified' => 'reports#verified_ministries'
  get '/reports/organizations/control' => 'reports#control_organizations'
  get '/reports/organizations/verified' => 'reports#verified_organizations'
  get '/reports/categories/rootstatus' => 'reports#root_category_totals'
  get '/reports/categories/rootstatus/csv' => 'reports#root_category_totals_csv'
  get '/reports/categories/rootstatus/summary' => 'reports#root_category_totals_summary'
  get '/reports/recommendations/category' => 'reports#recommendation_categories'
  get '/reports/recommendations/category/csv' => 'reports#recommendation_categories_csv'
  get '/reports/recommendations/category/summary' => 'reports#recommendation_categories_summary'
  get '/reports/exports' => 'reports#exports'
  get '/reports/exports/all/csv' => 'reports#export_all_csv'
  #alhader
  get '/reports/rapport' => 'reports#rapport'
  get '/recommendations/rapport' => 'recommendations#rapport'
  root "audit_reports#index"
end

app/models/user.rb
class User < ApplicationRecord
  #using postgreSQL enum type: https://www.sitepoint.com/enumerated-types-with-activerecord-and-postgresql/
  enum role: {
    admin:  'admin',
    user:   'user',
    restricted_user: 'restricted_user'
  }

  has_many :audit_reports, dependent: :restrict_with_error
  belongs_to :organization

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :timeoutable

  app_role = {
      user:  'user',
      admin:   'admin',
      restricted_user: 'restricted_user'
  }

  def check_roles(current_user)
    unless current_user.admin?
      self.role = :user
    end
  end

  def self.to_option_values
    user_objects = self.order(:email)
    users = Hash.new
    user_objects.each do |u|
      users[u.first_name] = u.id
    end
    return users
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def index
    @users = User.where.not(:id => current_user.id)
    authorize @users
    respond_to do |format|
      format.html
      format.json { render json: @users, status: :ok }
    end
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    @user.role = 'admin'
    authorize @user
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    params[:user].delete(:role) if @user == current_user 
    params[:user].delete(:password) if params[:user][:password].blank? 
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    if @user.destroy
      redirect_to users_path
    else
      render 'edit'
    end
  end 
  private

  def user_params
     params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :organization_id, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def localized_roles
    Hash[User.roles.map { |k,v| [User.human_attribute_name("role.#{k}"), v] }]
  end
end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>


  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, t('errors.error')) %> 
        <%= t('errors.prohibited_user') %>
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label  :first_name %><br>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label  :last_name %><br>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label  :email %><br>
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <% if current_user.admin? %>
        <%= form.label :organization %><br>
        <%= form.collection_select :organization_id, Organization.order(:name),:id,:name,{ :class => "form-control" } %>
      <% end %>
    </div>
  </div>
  <% if current_page?(new_user_path) || @user.id == nil %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label  :password %><br>
        <%= form.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group col-md-6">
        <%= form.label  :password_confirmation %><br>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <% unless @user == current_user %>
        <%= form.label  :role %><br>
        <%= form.select :role, options_for_select(localized_roles, @user.role), {}, { :class => "form-control" } %>
      <% end %>
    </div>
  </div>
  
  <% if current_page?(new_user_path)%>
    <%= form.submit t('navigation.save', model: User.model_name.human), class: "btn btn-primary" %>
  <% else %>
    <%= form.submit t('navigation.save', model: User.model_name.human), class: "btn btn-primary" %>

  <% end %>
  <% if current_user.admin? %>
    <%= link_to t('navigation.cancel'), users_path, class: "btn btn-secondary" %>
  <% else %>
    <%= link_to t('navigation.cancel'), audit_reports_path, class: "btn btn-secondary" %>
  <% end %>
 
<% end %>

app/views/users/_password_form.html.erb
<%= form_with model: @user, local: true do |form| %>


  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, t('errors.error')) %> 
        <%= t('errors.prohibited_user') %>
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


      <%= form.hidden_field :email %>
 

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label  :password %><br>
      <%= form.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label  :password_confirmation %><br>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  
  <% if current_page?(new_user_path)%>
    <%= form.submit t('navigation.save', model: User.model_name.human), class: "btn btn-primary" %>
  <% else %>
    <%= form.submit t('navigation.save', model: User.model_name.human), class: "btn btn-primary" %>
  <% end %>
  <% if current_user.admin? %>
    <%= link_to t('navigation.cancel'), users_path, class: "btn btn-secondary" %>
  <% else %>
    <%= link_to t('navigation.cancel'), audit_reports_path, class: "btn btn-secondary" %>
  <% end %>
 
<% end %>

app/views/users/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('user.edit') %></h5>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="info-tab" data-toggle="tab" href="#info" role="tab" aria-controls="info" aria-selected="true">
          <%= t('user.info') %>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="password-tab" data-toggle="tab" href="#password" role="tab" aria-controls="password" aria-selected="false">
          <%= t('user.password') %>
        </a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <br/>
      <div class="tab-pane fade show active" id="info" role="tabpanel" aria-labelledby="info-tab">
        <%= render 'form' %>
      </div>
      <div class="tab-pane fade" id="password" role="tabpanel" aria-labelledby="password-tab">
        <% if @user == current_user %>
          <div class="alert alert-warning" role="alert">
            <%= t('user.password_alert') %>
          </div>
        <% end %>
        <%= render 'password_form' %>
      </div>
    </div>
    
  </div>
</div>

app/views/users/index.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('navigation.users') %></h5>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th><%=t('activerecord.attributes.user.first_name') %></th>
            <th><%=t('activerecord.attributes.user.last_name') %></th>
            <th><%=t('activerecord.attributes.user.email') %></th>
            <th><%=t('activerecord.attributes.user.organization') %></th>
            <th><%=t('activerecord.attributes.user.role') %></th>
            
            
            <th>
              <% if policy(User).create? %>
                <span  class="float-right"><%= link_to t('navigation.new_user'), new_user_path, class: "btn btn-success btn-sm" %></span>
              <% end %>
            </th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |u| %>
          <tr>
            <td><%= link_to u.first_name, user_path(u) %></td>
            <td><%= link_to u.last_name, user_path(u) %></td>
            <td><%= link_to u.email, user_path(u) %></td>
            <td><%= u.organization.name %></td>
            <td><%= User.human_attribute_name("role.#{u.role}")  %></td>
            
            <td>
              <% if policy(u).update? %>
                <span  class="float-right"><%= link_to t('navigation.edit'), edit_user_path(u), class: "btn btn-primary btn-sm" %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('user.add') %></h5>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= t('user.show') %></h5>
    <p>
    <strong><%=t('activerecord.attributes.user.first_name') %>:</strong>
    <%= @user.first_name %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.user.last_name') %>:</strong>
    <%= @user.last_name %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.user.email') %>:</strong>
    <%= @user.email %>
    </p>
    <p>
    <strong><%=t('activerecord.attributes.user.organization') %>:</strong>
    <%= @user.organization.name %>
    </p>

    <% if policy(@user).update? %>
      <%= link_to t('navigation.edit'), edit_user_path(@user), class: "btn btn-primary"  %>
    <% end %>
    <% if current_user.admin? %>
      <%= link_to t('navigation.back'), users_path, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to t('navigation.back'), audit_reports_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>